events {}

http {
    include /etc/nginx/mime.types;
    client_max_body_size 500M;

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api_container:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /stream/ {
            alias /storage/processed/;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
        }
    }
}